export enum MovProdAcao {
  CRIACAO = 'CRIACAO',
  ATUALIZACAO = 'ATUALIZACAO',
  EXCLUSAO = 'EXCLUSAO'
}

export enum MovProdCampo {
  NOME = 'NOME',
  CODBARRA = 'CODBARRA',
  QUANTIDADE = 'QUANTIDADE',
  PRECOCUSTO = 'PRECOCUSTO',
  PRECOVENDA = 'PRECOVENDA',
  NENHUM = 'NENHUM'
}